version: 2.1

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_deploy

jobs:
  build_and_deploy:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and deploy Docker
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin https://registry.alexhicks.net
            docker build -t "$DOCKER_REPO:latest" .
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker push "$DOCKER_REPO:latest"
            fi
